version: 2
updates:
  # Node dependencies
  - package-ecosystem: npm
    directories:
      - /app/frontend
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
      all:
        patterns:
          - "*"

  # Python dependencies
  - package-ecosystem: pip
    directories:
      - /app/backend
      - /src/data-pipeline
      - /src/embedding-model
      - /src/construct-qa
      - /src/finetune-model
    schedule:
      interval: monthly
    labels:
      - dependencies
    groups:
      all:
        patterns:
          - "*"

  # GitHub Actions dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
