- name: Build and push Docker images to Artifact Registry
  hosts: localhost
  gather_facts: false

  vars:
    registry_base: "{{ gcp_region }}-docker.pkg.dev/{{ gcp_project_id }}/docker"

  tasks:
  - name: Set timestamp as Docker image tag
    shell: date +%Y%m%d%H%M%S
    register: docker_tag

  - name: Build frontend image
    community.docker.docker_image:
      build:
        path: /app/frontend
        platform: linux/amd64/v2
      name: "{{ registry_base }}/{{ frontend_name }}:{{ docker_tag.stdout }}"
      source: build

  - name: Push frontend image
    community.docker.docker_image:
      name: "{{ registry_base }}/{{ frontend_name }}:{{ docker_tag.stdout }}"
      repository: "{{ registry_base }}/{{ frontend_name }}:{{ docker_tag.stdout }}"
      push: yes
      source: local

  - name: Remove frontend image locally
    community.docker.docker_image:
      name: "{{ registry_base }}/{{ frontend_name }}:{{ docker_tag.stdout }}"
      source: local
      state: absent

  - name: Build backend image
    community.docker.docker_image:
      build:
        path: /app/backend
        platform: linux/amd64/v2
      name: "{{ registry_base }}/{{ backend_name }}:{{ docker_tag.stdout }}"
      source: build

  - name: Push backend image
    community.docker.docker_image:
      name: "{{ registry_base }}/{{ backend_name }}:{{ docker_tag.stdout }}"
      repository: "{{ registry_base }}/{{ backend_name }}:{{ docker_tag.stdout }}"
      push: yes
      source: local

  - name: Remove backend image locally
    community.docker.docker_image:
      name: "{{ registry_base }}/{{ backend_name }}:{{ docker_tag.stdout }}"
      source: local
      state: absent

  - name: Save Docker tag
    shell: echo {{ docker_tag.stdout }} > .docker-tag
