services:
  # Backend service
  backend:
    build:
      context: ./backend
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/veritas-trial-service.json
      - FRONTEND_URL=http://localhost:8080
      - CHROMADB_HOST=${CHROMADB_HOST}
    ports:
      - "8001:8001"
    volumes:
      - ../secrets:/secrets
  # Frontend service
  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: http://localhost:8001
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  chroma-data:
    external: true
