all:
  vars:
    google_application_credentials: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"
    veritas_trial_service_credentials: "{{ lookup('env', 'VERITAS_TRIAL_SERVICE_CREDENTIALS') }}"
    gcp_project_id: "{{ lookup('env', 'GCP_PROJECT_ID') }}"
    gcp_region: "{{ lookup('env', 'GCP_REGION') }}"
    gcp_zone: "{{ lookup('env', 'GCP_ZONE') }}"
    gcp_auth_kind: serviceaccount
    frontend_name: veritas-trial-frontend
    backend_name: veritas-trial-backend

  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
