all:
  vars:
    gcp_project_id: "{{ lookup('env', 'GCP_PROJECT_ID') }}"
    gcp_region: "{{ lookup('env', 'GCP_REGION') }}"
    frontend_name: veritas-trial-frontend
    backend_name: veritas-trial-backend

  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
