name: Deploy pipeline

on:
  workflow_dispatch:

jobs:
  deploy-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker client
        run: gcloud auth configure-docker

      - name: Build deployment container
        run: cd deploy && make build

      - name: Deploy pipeline
        env:
          VERITAS_TRIAL_SERVICE_CREDENTIALS: /tmp/veritas-trial-service.json
        run: |
          cd deploy
          printf "%s" "${{ secrets.VERITAS_TRIAL_SERVICE_KEY }}" > /tmp/veritas-trial-service.json
          make gh-actions command=./deploy-pipeline.sh
          rm /tmp/veritas-trial-service.json

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.CHARLIE_XIAO_PAT }}
          labels: ci/cd
          title: "cd: updates of pipeline deployment"
          commit-message: "cd: updates of pipeline deployment"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          committer: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          body: |
            This PR was triggered by @${{ github.actor }} in ${{ github.workflow }}.
            Check the workflow run at: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Enable auto-merge
        run: gh pr merge --squash --auto "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.CHARLIE_XIAO_PAT }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pull-request-number }}
