name: Deploy app

on:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker client
        run: gcloud auth configure-docker

      - name: Build deployment container
        run: cd deploy && make build

      - name: Deploy app
        env:
          VERITAS_TRIAL_SERVICE_KEY: ${{ secrets.VERITAS_TRIAL_SERVICE_KEY }}
        run: cd deploy && make gh-actions command=./deploy-app.sh

      - name: Update Docker tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "cd: Update Docker tag

          Triggered by ${{ github.actor }} in ${{ github.workflow }}. Workflow run at:
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git push
