name: Deploy app

on:
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google authentification
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker client
        run: gcloud auth configure-docker

      - name: Build deployment container
        run: cd deploy && make build

      - name: Deploy app
        run: |
          cd deploy
          docker container run --rm \
            --env GCP_PROJECT_ID=veritastrial \
            --env GCP_REGION=us-central1 \
            --volume ${{ github.workspace }}/app/backend:/app/backend:ro \
            --volume ${{ github.workspace }}/app/frontend:/app/frontend:ro \
            --volume /var/run/docker.sock:/var/run/docker.sock \
            --name veritas-trial-deployment veritas-trial-deployment ./deploy-app.sh
