name: Formatting and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pipenv

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Node setup and cache
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          cache-dependency-path: app/frontend/pnpm-lock.yaml

      - name: Install development dependencies
        run: cd app && make devinstall

      - name: Check code formatting and linting
        run: cd app && make devlintcheck
